### ISSUE TITLE
async/await support

### ISSUE THREAD

**Issue by mgenev** [alexmingoia/koa-router#130]
I enabled async/await per this conversation https://github.com/koajs/koa/issues/415
Everything's working, except when I get this module involved and switch my functions from generator to async, I start getting `undefined is not a function` coming out of this module, I suspect it's not async/await compliant?

**Comment by alexmingoia** [comment]
Works fine for me using `babel`. What are you using to transform?

**Comment by mgenev** [comment]
Babe as well, do you have an example where I can see it working?  Mine is public
Works for all the other middleware, but if I switch these routes to async/await from */yield It breaks.
https://github.com/mgenev/nautilus/blob/async/server/controllers/post.js

Here is the babel setup:
https://github.com/mgenev/nautilus/blob/async/server/run.js

I also tried using 'asyncToGenerator' instead of bluebird, different error but also breaks...

**Comment by mgenev** [comment]
Just tried again, this works as intended:

```
import koa from 'koa';
var router = require('koa-router')();
let app = koa();

app.experimental = true;

router.get('/meh',  function* (next) {
  this.body = 'MEH MEH MEH';
});

app.use(router.routes()).use(router.allowedMethods());
app.server = app.listen(3000);
```
this:
```
import koa from 'koa';
var router = require('koa-router')();
let app = koa();

app.experimental = true;

router.get('/meh',  async function (next) {
  this.body = 'MEH MEH MEH';
});

app.use(router.routes()).use(router.allowedMethods());
app.server = app.listen(3000);
```
gives me error:
```
  TypeError: next[(intermediate value)] is not a function
      at Object.dispatch (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa-router/lib/router.js:331:14)
      at GeneratorFunctionPrototype.next (native)
      at Object.respond (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/lib/application.js:180:10)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/node_modules/co/index.js:64:19)
      at /Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/node_modules/co/index.js:53:5
      at Object.co (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/node_modules/co/index.js:49:10)
      at Wrap.<anonymous> (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/node_modules/composition/index.js:48:19)
      at Wrap.Object.defineProperty.get (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/node_modules/composition/node_modules/memorizer/index.js:5:38)
      at Wrap.catch (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/node_modules/composition/index.js:98:14)
      at Server.<anonymous> (/Users/martin.genev/Projects/temp/asynckoa/node_modules/koa/lib/application.js:128:23)
      at emitTwo (events.js:87:13)
      at Server.emit (events.js:169:7)
      at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:471:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
      at Socket.socketOnData (_http_server.js:322:22)
```

my babel settings:
```
require('babel/register')({
  optional: ['asyncToGenerator']
});
```

What am I doing wrong? How were you able to get it to work?

**Comment by bernhardw** [comment]
It would be great to have support for async functions as well.

**Comment by geddski** [comment]
I'd like this as well :+1:

**Comment by juhaelee** [comment]
:+1:

**Comment by mvila** [comment]
I am switching all my projects from ES6 generators to ES7 async functions... So, a big :+1: for me too!

**Comment by dvlsg** [comment]
:+1: This functionality would get me to move all of my projects to koa as soon as it is available. Would be a fantastic feature.

**Comment by ujenjt** [comment]
:+1: really need this feature

**Comment by niieani** [comment]
:+1: Would be awesome.

**Comment by xmlking** [comment]
:+1:

**Comment by menems** [comment]
Hi everyone,

So as I understand this commit is for the experimetal option on koa master branch? not for the new signature proposal with ctx on params?

**Comment by alexmingoia** [comment]
The experimental option.
