### ISSUE TITLE
Cannot read property 'routerPath' of undefined

### ISSUE THREAD

**Issue by christiansakai** [alexmingoia/koa-router#147]
Hi,

I try to integrate koa with koa-router using babel/register for ES6.  Here is my code
``` 
// app.js
import koa from 'koa';
import logger from 'koa-logger';
import routes from './routes';
const app = koa();

app.use(logger()); //Todo use morgan on production
app.use(routes());

const port = 3000; //Todo use app.set
app.listen(port);
console.log(`Server is listening on port ${port}`);
```

```
// routes.js
import Router from 'koa-router';
const router = Router();

router.get('/', function *(next) {
  this.body = 'Hello World!!!';
});

export default router.routes;
```

This is what I got
```
  TypeError: Cannot read property 'routerPath' of undefined
      at Object.dispatch (/Users/christiansakai/Desktop/react/overreact/node_modules/koa-router/lib/router.js:316:27)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:65:19)
      at /Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:54:5
      at new Promise (/Users/christiansakai/Desktop/react/overreact/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
      at Object.co (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:50:10)
      at Object.toPromise (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:118:63)
      at next (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:69:7)
      at /Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:54:5
```

But, this code below works
```
// app.js
import koa from 'koa';
import logger from 'koa-logger';
import router from './routes';
const app = koa();

app.use(logger()); //Todo use morgan on production
app.use(router.routes());

const port = 3000; //Todo use app.set
app.listen(port);
console.log(`Server is listening on port ${port}`);
```

```
//routes.js
import Router from 'koa-router';
const router = Router();

router.get('/', function *(next) {
  this.body = 'Hello World!!!';
});

export default router;
```

am I missing something?

**Comment by neVERberleRfellerER** [comment]
`export default router.routes;`
should be
`export default router.routes.bind(router);`

Without bind, `this` used in `routes` function is not router instance.

More info there
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
in the "Creating a bound function" section.

**Comment by christiansakai** [comment]
Ahh, thank you so much! it worked
