### ISSUE TITLE
this bug is so weird

### ISSUE THREAD

**Issue by christiansakai** [alexmingoia/koa-router#149]
Hi,

Basically, this is working
```
var hello = function* (next) {
  this.body = 'hello world';
};

koaRouter.get('/', hello);
```

this is NOT working
```
var helloo = function* (next) {
  this.body = 'helloo world';
};

koaRouter.get('/', helloo);
```

But this IS working
```
function* helloo(next) {
  this.body = 'helloo world';
}

koaRouter.get('/', helloo);
```

I am using babel to transpile my code written in ES6.

Here is the error stack
```
ReferenceError: helloo is not defined
      at Object.helloo (/Users/christiansakai/Desktop/react/overreact/server/routes.js:31:5)
      at Object.dispatch (/Users/christiansakai/Desktop/react/overreact/node_modules/koa-router/lib/router.js:332:39)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:65:19)
      at /Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:54:5
      at new Promise (/Users/christiansakai/Desktop/react/overreact/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
      at Object.co (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:50:10)
      at Object.toPromise (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:118:63)
      at next (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:99:29)
      at onFulfilled (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:69:7)
      at /Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:54:5
      at new Promise (/Users/christiansakai/Desktop/react/overreact/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:182:7)
      at Object.co (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:50:10)
      at Object.createPromise (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/node_modules/co/index.js:30:15)
      at Server.<anonymous> (/Users/christiansakai/Desktop/react/overreact/node_modules/koa/lib/application.js:128:8)
      at Server.emit (events.js:110:17)
```

**Comment by ajuste** [comment]
@christiansakai seems more related to babel than koa-router. Have you tried using that on a non koa-router scenario?

**Comment by christiansakai** [comment]
@ajuste 
Yes, when I use it in regular Koa (without using koa-router), it worked just fine.

**Comment by buzinas** [comment]
Why the label "won't fix" for this?

**Comment by alexmingoia** [comment]
This is a problem with babel not koa-router. Show me how it's a problem with koa-router and I'll fix it. AFAIK all the code in koa-router is 100% valid ES6.

**Comment by ami44** [comment]
I have no problem with babel + koa + koa-router

```
npm install -g babel
babel-node --harmony start.js
```
