### ISSUE TITLE
path of router.use() method can be a RegExp?

### ISSUE THREAD

**Issue by XuJinNet** [alexmingoia/koa-router#220]
i `m set a regexp to router.use(), got a error:
> Error:  `(.*)`: `middleware` must be a function, not `object`
>     at Layer.<anonymous> (...\node_modules\koa-router\lib\layer.js:38:13)
>     at Array.forEach (native)
>     at new Layer (...\node_modules\koa-router\lib\layer.js:35:14)
>     at Router.register (...\node_modules\koa-router\lib\router.js:503:15)
>     at Router.use (...\node_modules\koa-router\lib\router.js:256:12)

**Comment by alexmingoia** [comment]
Regular expressions aren't supported. There are a number of features that would need to be slightly refactored to support regular expressions (nested routes and parameter matching to name a few).

**Comment by cb1kenobi** [comment]
I ran just ran into this. +1 to supporting this feature someday.
