### ISSUE TITLE
this.state props is undefined after rendering

### ISSUE THREAD

**Issue by zombofrog** [alexmingoia/koa-router#269]
Here is my server: 

```
var app = require('koa')();
var router = require('koa-router')();

var port = 3003;

router.get('home', '/', function * (next) {
  this.state.props = { page: 'home' };
  yield next;
});

app.use(router.routes())
   .use(router.allowedMethods())
   .use(function * () {
     console.log('log: ', this.state);
     this.body = this.state.props.page;
   });

app.listen(port);
```

All works correctly, but after rendering '/' page I got a such error in console:

```
log:  { props: { page: 'home' } }
log:  {}

  TypeError: Cannot read property 'page' of undefined
      at Object.<anonymous> (c:\Boxes\projects\react-server-side\bin\server.js:15:34)
      at next (native)
      at Object.allowedMethods (c:\Boxes\projects\react-server-side\node_modules\koa-router\lib\router.js:374:12)
      at next (native)
      at Object.dispatch (c:\Boxes\projects\react-server-side\node_modules\koa-router\lib\router.js:336:14)
      at next (native)
      at Object.<anonymous> (c:\Boxes\projects\react-server-side\node_modules\koa\node_modules\koa-compose\index.js:28:19)
      at next (native)
      at onFulfilled (c:\Boxes\projects\react-server-side\node_modules\koa\node_modules\co\index.js:65:19)
      at c:\Boxes\projects\react-server-side\node_modules\koa\node_modules\co\index.js:54:5
```

Why last generator calls second time whiout my props in ctx.state?

**Comment by jbielick** [comment]
What version of koa, koa-router are you using? 

I created a simple test case for this that looks like the following:

```js
var koa = require('koa')
var app = new koa();
var router = require('koa-router')();
var assert = require('assert');
var request = require('supertest');

router.get('home', '/', function * (next) {
  this.state.props = { page: 'home' };
  yield next;
});

app.use(router.routes())
   .use(router.allowedMethods())
   .use(function * () {
     this.body = this.state.props.page;
   });

request(app.listen())
  .get('/')
  .expect(200)
  .end((err, res) => {
    assert(res.text == 'home');
    process.exit(0);
  });

```

```json
    "koa": "1.2.4",
    "koa-router": "5.4.0",
    "supertest": "2.0.0"
```

and it works just fine.
