### ISSUE TITLE
Nested router allowedMethods()  returns undefined if the middleware is not a generator function

### ISSUE THREAD

**Issue by nivekz** [alexmingoia/koa-router#321]
- node: 6.9.2
- koa: 1.2.4
- koa-router: 5.4.0

```
const koa = require('koa');
const router = require('koa-router');

const app = koa();
const rootRouter = router();
const fooRouter = router();

fooRouter.get('/', function index() {
  this.body = 'Hello World';
});

rootRouter.use('/foo', fooRouter.routes(), fooRouter.allowedMethods());

app
  .use(rootRouter.routes())
  .use(rootRouter.allowedMethods());

app.listen(3000);
```

Visiting `/foo` gives the following error:
```
  TypeError: undefined is not a function
      at Object.allowedMethods (/Users/Kevin/workspace/nodejs/m/node_modules/koa-router/lib/router.js:374:12)
      at next (native)
      at Object.dispatch (/Users/Kevin/workspace/nodejs/m/node_modules/koa-router/lib/router.js:336:14)
      at next (native)
      at Object.<anonymous> (/Users/Kevin/workspace/nodejs/m/node_modules/koa-compose/index.js:28:19)
      at next (native)
      at onFulfilled (/Users/Kevin/workspace/nodejs/m/node_modules/co/index.js:65:19)
      at /Users/Kevin/workspace/nodejs/m/node_modules/co/index.js:54:5
      at Object.co (/Users/Kevin/workspace/nodejs/m/node_modules/co/index.js:50:10)
      at Object.createPromise (/Users/Kevin/workspace/nodejs/m/node_modules/co/index.js:30:15)
```

**Comment by Disorrder** [comment]
Same here

node: 7.6.0
koa: 2.2.0
koa-router: 7.1

**Comment by bigmeech** [comment]
Hi @nivekz! were you ever able to resolve this issue?
