### ISSUE TITLE
A simple `get` router is making a internal server error response

### ISSUE THREAD

**Issue by LucasBadico** [alexmingoia/koa-router#448]
```js
import Koa from 'koa'
import Router from 'koa-router'
import { Sockend } from 'cote'
import { createServer } from 'http'
import socket from 'socket.io'


const app = new Koa()
const router = new Router()
const server = createServer(app.callback())
const io = socket(server)

router.get('/hello', (cxt, next) => {
    console.log(JSON.stringify({cxt, next}, null, 4))
    ctx.body = 'Hello World! from koa-router'
    return next();
})

app.keys = ['im a newer secret', 'i like turtle'];
// app.use(async ctx => {
//     ctx.body = 'Hello World!, from koa';
//   });
app.use(router.routes())
app.use(router.allowedMethods())



server.listen(5001);



new Sockend(io, {
    name: 'calculator sockend server'
});

export {
    server,
    app,
    router,
    io,
}
export default app
```

```json
{
  "name": "beechallenge",
  "version": "1.0.0",
  "description": "A small challenge proposed by beeTech team.",
  "main": "index.js",
  "scripts": {
    "test": "jest --colors -b --verbose",
    "dev": "babel-node"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/LucasBadico/beeChallenge.git"
  },
  "keywords": [
    "microservices",
    "react",
    "react-native"
  ],
  "author": "LucasBadico",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/LucasBadico/beeChallenge/issues"
  },
  "homepage": "https://github.com/LucasBadico/beeChallenge#readme",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-loader": "^7.1.4",
    "babel-plugin-ramda": "^1.4.3",
    "babel-plugin-react-element-info": "^1.0.1",
    "babel-plugin-reflective-import": "^1.1.0",
    "babel-plugin-relative-import": "^1.0.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-inline-environment-variables": "^0.3.0",
    "babel-plugin-transform-node-env-inline": "^0.3.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "enzyme": "^3.3.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
    "jest-webpack-alias": "^3.3.3",
    "babel-cli": "^6.26.0",
    "babel-jest": "^22.4.3",
    "babel-plugin-module-resolver": "^3.1.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "co-supertest": "^0.0.10",
    "react-hot-loader": "^4.0.0",
    "enzyme-adapter-react-16": "^1.1.1"    
  },
  "dependencies": {
    "cote": "^0.16.2",
    "global": "^4.3.2",
    "jest": "^22.4.3",
    "koa": "^2.5.0",
    "koa-router": "^7.4.0",
    "moment": "^2.17.0",
    "ramda": "^0.25.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "rxjs": "^5.4.3",
    "socket.io": "^2.0.4",
    "supertest": "^3.0.0"
  },
  "engines": {
    "node": ">=7.0.0",
    "npm": ">=4.1.2"
  },
  "jest": {
    "moduleNameMapper": {
      "\\.(css|jpg|png|scss)$": "<rootDir>/empty-module.js"
    },
    "setupFiles": [
      "./jest-setup.js"
    ],
    "modulePaths": [
      "<rootDir>/node_modules",
      "<rootDir>/__tests__"
    ],
    "testMatch": [
      "**/?(*.)(spec).jsx",
      "**/?(*.)(spec).js"
    ]
  },
  "husky": {
    "hooks": {
      "pre-push": "npm run format-on-commit && npm run test"
    }
  }
}
```

```js
import {
    server,
    app,
} from '$/ddd-calculator'

import httpRequester from 'supertest'

const request = httpRequester.agent(server)

describe('Calculator app', () => {
    it('should have a default \'Hello World! from koa\'', async done => {
        expect.assertions(1)
        const helloFromApp = await request.get('/hello')     
        console.log(helloFromApp)  
        expect(helloFromApp).toEqual('Hello World! from koa')
        done()
    })
  })

```

```bash

yarn test __tests__/microservices/ddd-calculator/ddd-calculator
yarn run v1.5.1
warning ../package.json: No license field
$ jest --colors -b --verbose __tests__/microservices/ddd-calculator/ddd-calculator
  console.warn node_modules/node-uuid/uuid.js:48
    [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()

  console.log node_modules/cote/dist/components/discovery.js:68
    
    Hello! I'm calculator sockend server#6d73dc00-390c-49ac-b4ab-c5c955782270 
    ========================
    

 FAIL  __tests__/microservices/ddd-calculator/ddd-calculator.spec.js
  Calculator app
    ✕ should have a default 'Hello World! from koa' (87ms)

  ● Calculator app › should have a default 'Hello World! from koa'

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "Hello World! from koa"
    Received:
      {"header": {"connection": "close", "content-length": "21", "content-type": "text/plain; charset=utf-8", "date": "Sat, 24 Mar 2018 23:15:30 GMT"}, "req": {"data": undefined, "headers": {"user-agent": "node-superagent/3.8.2"}, "method": "GET", "url": "http://127.0.0.1:5001/hello"}, "status": 500, "text": "Internal Server Error"}
    
    Difference:
    
      Comparing two different types of values. Expected string but received object.

      13 |         const helloFromApp = await request.get('/hello')     
      14 |         console.log(helloFromApp)  
    > 15 |         expect(helloFromApp).toEqual('Hello World! from koa')
      16 |         done()
      17 |     })
      18 |   })
      
      at _callee$ (__tests__/microservices/ddd-calculator/ddd-calculator.spec.js:15:30)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (__tests__/microservices/ddd-calculator/ddd-calculator.spec.js:11:191)
      at __tests__/microservices/ddd-calculator/ddd-calculator.spec.js:11:361

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.981s
Ran all test suites matching /__tests__\/microservices\/ddd-calculator\/ddd-calculator/i.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c jest --colors -b --verbose __tests__/microservices/ddd-calculator/ddd-calculator
Directory: /Users/badicomac/Repositorios/beeChallenge
Output:
".

```

**Comment by jbielick** [comment]
You have quite a lot of code here that isn't related to koa-router. Have you tried creating a simple test case not involving the other code? That might help you narrow down where the error is occurring. Are you watching the server logs? They may be hidden by super agent. Koa's error emitter would emit an event if an error was occurring in one of middleware (which is indicative of the 500 status). 

It seems unlikely that a router library would break on the simplest of functions, right? I noticed you have used an undefined variable in your get handler 

```
router.get('/hello', (cxt
```

Did you mean to use the variable name "cxt"? On the next line you refer to a variable "ctx".

**Comment by LucasBadico** [comment]
@jbielick sorry, was the typo the problem. Thanks!

**Comment by basickarl** [comment]
How does one catch unhandled errors server side? For example like koajs app.on('error'...)
